# Generated by Django 4.1.6 on 2023-02-14 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matatu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('registration', models.CharField(max_length=20)),
                ('routes', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('avatar', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('matatu', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.matatu')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=5)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.user')),
                ('matatu', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.matatu')),
            ],
        ),
        migrations.CreateModel(
            name='Sacco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.route')),
                ('trips', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.trips')),
            ],
        ),
        migrations.AddField(
            model_name='matatu',
            name='conductor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='conductor', to='base.user'),
        ),
        migrations.AddField(
            model_name='matatu',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='driver', to='base.user'),
        ),
    ]
